// Kenya NSE Companies — Embedded Financial Data
// Auto-generated by backend/populate.py
// Values: KES thousands (banks) or KES millions (SCOM)
// Source: NSE disclosure PDFs

const NSE_COMPANIES = {

  KCB: {
    name: "KCB Group PLC",
    ticker: "KCB",
    exchange: "NSE",
    sector: "Banking",
    logo: "\ud83c\udfe6",
    currency: "KES",
    units: "thousands",
    latestPrice: 42.0,
    latestPeriod: {"year": 2025, "period": "Q Sep2025", "periodType": "quarter", "revenue": 98811027.0, "pat": null, "pbt": null, "nii": 72146888.0, "eps": 18.0, "dps": 19.0, "totalAssets": 1404190326.0, "totalEquity": 210325777.0, "deposits": 1062960998.0, "loans": 850344983.0, "ebitda": null, "mpesa": null},
    annuals: [
      {"year": 2020, "period": "Dec2020", "periodType": "annual", "revenue": 75842577.0, "pat": 18346857.0, "pbt": 25589.0, "nii": 53470863.0, "eps": 0.34, "dps": 0.17, "totalAssets": 758345431.0, "totalEquity": 111270544.0, "deposits": 588627915.0, "loans": 492537561.0, "ebitda": null, "mpesa": null},
      {"year": 2023, "period": "Dec2023", "periodType": "annual", "revenue": 98100692.0, "pat": 25410014.0, "pbt": 33252179.0, "nii": 64774792.0, "eps": 0.47, "dps": 0.58, "totalAssets": 1425369827.0, "totalEquity": 138717804.0, "deposits": 1116875397.0, "loans": 740241723.0, "ebitda": null, "mpesa": null},
      {"year": 2024, "period": "Dec2024", "periodType": "annual", "revenue": 126653268.0, "pat": 45029313.0, "pbt": 58375497.0, "nii": 88856198.0, "eps": 0.83, "dps": 0.24, "totalAssets": 1277766539.0, "totalEquity": 183715437.0, "deposits": 971960594.0, "loans": 736614026.0, "ebitda": null, "mpesa": null}
    ],
    quarters: [
      {"year": 2024, "period": "Q Mar2024", "periodType": "quarter", "revenue": 30750467.0, "pat": 11169312.0, "pbt": 14619526.0, "nii": 20506602.0, "eps": 0.83, "dps": null, "totalAssets": 1327838470.0, "totalEquity": 151141853.0, "deposits": 997078186.0, "loans": 698236955.0, "ebitda": null, "mpesa": null},
      {"year": 2024, "period": "H1 Jun2024", "periodType": "half_year", "revenue": 59454682.0, "pat": 21223377.0, "pbt": 27247302.0, "nii": 39882688.0, "eps": 0.79, "dps": 0.12, "totalAssets": 1296698247.0, "totalEquity": 158799444.0, "deposits": 978413046.0, "loans": 710046556.0, "ebitda": null, "mpesa": null},
      {"year": 2024, "period": "Q Sep2024", "periodType": "quarter", "revenue": 88572537.0, "pat": null, "pbt": null, "nii": 59849018.0, "eps": null, "dps": null, "totalAssets": 1325023040.0, "totalEquity": 164429835.0, "deposits": 1033725604.0, "loans": 726954611.0, "ebitda": null, "mpesa": null},
      {"year": 2025, "period": "Q Mar2025", "periodType": "quarter", "revenue": 31526092.0, "pat": 11067572.0, "pbt": 14517952.0, "nii": 22448350.0, "eps": 0.82, "dps": 0.24, "totalAssets": 1329508593.0, "totalEquity": 195390252.0, "deposits": 1007061773.0, "loans": 760298000.0, "ebitda": null, "mpesa": null},
      {"year": 2025, "period": "H1 Jun2025", "periodType": "half_year", "revenue": 64286686.0, "pat": 22874591.0, "pbt": 28400754.0, "nii": 46703444.0, "eps": 0.85, "dps": 0.12, "totalAssets": 1351345471.0, "totalEquity": 206119370.0, "deposits": 1031466777.0, "loans": 808894832.0, "ebitda": null, "mpesa": null},
      {"year": 2025, "period": "Q Sep2025", "periodType": "quarter", "revenue": 98811027.0, "pat": null, "pbt": null, "nii": 72146888.0, "eps": 18.0, "dps": 19.0, "totalAssets": 1404190326.0, "totalEquity": 210325777.0, "deposits": 1062960998.0, "loans": 850344983.0, "ebitda": null, "mpesa": null}
    ],
  }

};
