// Kenya NSE Companies -- Embedded Financial Data
// Auto-generated by backend/populate.py
// Units: Revenue/NII/PAT in KES thousands (except Safaricom = KES millions)
// Source: NSE annual results PDFs

const NSE_COMPANIES = {

  ABSA: {
    name: "ABSA Bank Kenya PLC",
    ticker: "ABSA",
    exchange: "NSE",
    sector: "Banking",
    currency: "KES",
    units: "thousands",
    latestPrice: 14.2,
    annuals: [
      { year: 2021, period: "Dec2021", revenue: 33585983, pat: null, pbt: 8299860, nii: 23280874, eps: 0.69, dps: 1.10, totalAssets: 377935772, totalEquity: 44969283, deposits: 31393575, loans: null, ebitda: null },
      { year: 2023, period: "Dec2023", revenue: 44555765, pat: 13867886, pbt: 19832431, nii: 32131322, eps: 2.55, dps: 1.35, totalAssets: 477290548, totalEquity: 60811301, deposits: 7114100, loans: null, ebitda: null },
    ]
  },

  STANCHART: {
    name: "Standard Chartered Bank Kenya",
    ticker: "SCBK",
    exchange: "NSE",
    sector: "Banking",
    currency: "KES",
    units: "thousands",
    latestPrice: 195.0,
    annuals: [
      { year: 2023, period: "Dec2023", revenue: 33977048, pat: 12057935, pbt: 17103199, nii: 22223065, eps: 31.47, dps: 22, totalAssets: 381260015, totalEquity: 56136730, deposits: 278879309, loans: 139412560, ebitda: null },
      { year: 2024, period: "Dec2024", revenue: 41728586, pat: 13835467, pbt: 19668482, nii: 29325087, eps: 36.17, dps: 29, totalAssets: 428962175, totalEquity: 61532267, deposits: 342853241, loans: 163161777, ebitda: null },
    ]
  },

  SAFARICOM: {
    name: "Safaricom PLC",
    ticker: "SCOM",
    exchange: "NSE",
    sector: "Telecom",
    currency: "KES",
    units: "millions",
    latestPrice: 15.85,
    annuals: [
      { year: 2019, period: "Mar2019", revenue: null, pat: null, pbt: null, nii: null, eps: null, dps: null, totalAssets: null, totalEquity: null, deposits: null, loans: null, ebitda: null },
      { year: 2020, period: "Mar2020", revenue: 251.22, pat: 73.66, pbt: 105.77, nii: null, eps: 1.84, dps: 1.40, totalAssets: null, totalEquity: 143.08, deposits: null, loans: null, ebitda: 138.04 },
      { year: 2023, period: "Mar2023", revenue: 295692.30, pat: 52482.87, pbt: 88345.20, nii: null, eps: 1.55, dps: 1.20, totalAssets: 509207, totalEquity: 263365.90, deposits: null, loans: null, ebitda: 139862.40 },
      { year: 2024, period: "Mar2024", revenue: 335353.10, pat: 42658.45, pbt: 84687.49, nii: null, eps: 1.57, dps: null, totalAssets: 641164.30, totalEquity: 335747.90, deposits: null, loans: null, ebitda: -12776.50 },
    ]
  },

};
