// Kenya NSE Companies — Embedded Financial Data
// Auto-generated by backend/populate.py
// Values: KES thousands (banks) or KES millions (SCOM)
// Source: NSE disclosure PDFs

const NSE_COMPANIES = {

  ABSA: {
    name: "ABSA Bank Kenya PLC",
    ticker: "ABSA",
    exchange: "NSE",
    sector: "Banking",
    logo: "\ud83c\udfe6",
    currency: "KES",
    units: "thousands",
    latestPrice: 14.2,
    latestPeriod: {"year": 2025, "period": "Q Sep2025", "periodType": "quarter", "revenue": 45130347.0, "pat": 13797373.0, "pbt": 19707542.0, "nii": null, "eps": 2.54, "dps": 1.75, "totalAssets": 483844138.0, "totalEquity": 72606766.0, "deposits": 13782250.0, "loans": 311460505.0, "ebitda": null, "mpesa": null},
    annuals: [
      {"year": 2021, "period": "Dec2021", "periodType": "annual", "revenue": 33585983.0, "pat": 10869969.0, "pbt": 8299860.0, "nii": 23280874.0, "eps": 0.69, "dps": 1.1, "totalAssets": 377935772.0, "totalEquity": 44969283.0, "deposits": 31393575.0, "loans": 208854694.0, "ebitda": null, "mpesa": null},
      {"year": 2023, "period": "Dec2023", "periodType": "annual", "revenue": 44555765.0, "pat": 13867886.0, "pbt": 19832431.0, "nii": 32131322.0, "eps": 2.55, "dps": 1.35, "totalAssets": 477290548.0, "totalEquity": 60811301.0, "deposits": 7114100.0, "loans": 283578543.0, "ebitda": null, "mpesa": null}
    ],
  },

  BOC: {
    name: "BOC Kenya PLC",
    ticker: "BOC",
    exchange: "NSE",
    sector: "Manufacturing",
    logo: "\ud83c\udfed",
    currency: "KES",
    units: "thousands",
    latestPrice: 95.0,
    latestPeriod: {"year": 2023, "period": "H1 Jun2023", "periodType": "half_year", "revenue": 589987.0, "pat": null, "pbt": 71635.0, "nii": null, "eps": 2.58, "dps": null, "totalAssets": 7252.0, "totalEquity": 1743492.0, "deposits": null, "loans": null, "ebitda": null, "mpesa": null},
    annuals: [
      {"year": 2020, "period": "Dec2020", "periodType": "annual", "revenue": 1098104.0, "pat": 101656.0, "pbt": null, "nii": null, "eps": 5.21, "dps": null, "totalAssets": 35883.0, "totalEquity": 1607568.0, "deposits": null, "loans": null, "ebitda": null, "mpesa": null},
      {"year": 2023, "period": "Dec2023", "periodType": "annual", "revenue": 1539342.0, "pat": 198058.0, "pbt": 309081.0, "nii": null, "eps": 10.14, "dps": null, "totalAssets": 39366.0, "totalEquity": 1807496.0, "deposits": null, "loans": null, "ebitda": null, "mpesa": null}
    ],
  },

  BRIT: {
    name: "Britam Holdings PLC",
    ticker: "BRIT",
    exchange: "NSE",
    sector: "Insurance",
    logo: "\ud83c\udfe2",
    currency: "KES",
    units: "thousands",
    latestPrice: 6.0,
    latestPeriod: {"year": 2024, "period": "H1 Jun2024", "periodType": "half_year", "revenue": null, "pat": 2012920.0, "pbt": 2810674.0, "nii": null, "eps": 0.8, "dps": null, "totalAssets": 188823941.0, "totalEquity": 26595507.0, "deposits": null, "loans": null, "ebitda": null, "mpesa": null},
    annuals: [
      {"year": 2023, "period": "Dec2023", "periodType": "annual", "revenue": 36.4, "pat": 3279119.0, "pbt": 4.82, "nii": null, "eps": null, "dps": null, "totalAssets": 174393970.0, "totalEquity": 25.7, "deposits": null, "loans": null, "ebitda": null, "mpesa": null}
    ],
  },

  CARB: {
    name: "Carbacid Investments PLC",
    ticker: "CARB",
    exchange: "NSE",
    sector: "Manufacturing",
    logo: "\ud83c\udfed",
    currency: "KES",
    units: "thousands",
    latestPrice: 12.0,
    annuals: [
      {"year": 2020, "period": "Jan2020", "periodType": "annual", "revenue": 352912.0, "pat": 178688.0, "pbt": 232585.0, "nii": null, "eps": 0.7, "dps": null, "totalAssets": null, "totalEquity": 3514232.0, "deposits": null, "loans": null, "ebitda": null, "mpesa": null},
      {"year": 2021, "period": "Jan2021", "periodType": "annual", "revenue": 449652.0, "pat": 210415.0, "pbt": 276710.0, "nii": null, "eps": 0.83, "dps": 0.0, "totalAssets": 3855303.0, "totalEquity": null, "deposits": null, "loans": null, "ebitda": null, "mpesa": null},
      {"year": 2022, "period": "Jan2022", "periodType": "annual", "revenue": 701615.0, "pat": 360747.0, "pbt": 457978.0, "nii": null, "eps": 1.42, "dps": null, "totalAssets": null, "totalEquity": 528999.0, "deposits": null, "loans": null, "ebitda": null, "mpesa": null},
      {"year": 2023, "period": "Jan2023", "periodType": "annual", "revenue": 855525.0, "pat": 411650.0, "pbt": 548867.0, "nii": null, "eps": 1.62, "dps": null, "totalAssets": null, "totalEquity": 367031.0, "deposits": null, "loans": null, "ebitda": null, "mpesa": null},
      {"year": 2024, "period": "Jan2024", "periodType": "annual", "revenue": 1080477.0, "pat": 485162.0, "pbt": 646882.0, "nii": null, "eps": 1.9, "dps": null, "totalAssets": null, "totalEquity": 488110.0, "deposits": null, "loans": null, "ebitda": null, "mpesa": null},
      {"year": 2024, "period": "Jul2024", "periodType": "annual", "revenue": null, "pat": 843274.0, "pbt": 1123758.0, "nii": null, "eps": 3.2, "dps": null, "totalAssets": null, "totalEquity": 1.7, "deposits": null, "loans": null, "ebitda": null, "mpesa": null},
      {"year": 2025, "period": "Jul2025", "periodType": "annual", "revenue": 2099850.0, "pat": 1002914.0, "pbt": 1288564.0, "nii": null, "eps": 3.94, "dps": null, "totalAssets": null, "totalEquity": null, "deposits": null, "loans": null, "ebitda": null, "mpesa": null}
    ],
  },

  COOP: {
    name: "Co-operative Bank of Kenya",
    ticker: "COOP",
    exchange: "NSE",
    sector: "Banking",
    logo: "\ud83c\udfe6",
    currency: "KES",
    units: "thousands",
    latestPrice: 14.5,
    latestPeriod: {"year": 2025, "period": "Q Sep2025", "periodType": "quarter", "revenue": 67383790.0, "pat": null, "pbt": 1.0, "nii": 45277770.0, "eps": 3.68, "dps": 1.0, "totalAssets": 815266710.0, "totalEquity": 164162107.0, "deposits": 548575643.0, "loans": 406524191.0, "ebitda": null, "mpesa": null},
    annuals: [
      {"year": 2020, "period": "Dec2020", "periodType": "annual", "revenue": 53829689.0, "pat": 14528812.0, "pbt": null, "nii": 36348966.0, "eps": 1.98, "dps": 1.0, "totalAssets": 536945250.0, "totalEquity": 90725868.0, "deposits": 378630453.0, "loans": 286634192.0, "ebitda": null, "mpesa": null},
      {"year": 2023, "period": "Dec2023", "periodType": "annual", "revenue": 71692630.0, "pat": null, "pbt": null, "nii": 45230881.0, "eps": null, "dps": 1.5, "totalAssets": 671131286.0, "totalEquity": 113558596.0, "deposits": 451642048.0, "loans": 374227421.0, "ebitda": null, "mpesa": null},
      {"year": 2024, "period": "Dec2024", "periodType": "annual", "revenue": 18849176.0, "pat": null, "pbt": 4.44, "nii": null, "eps": 0.79, "dps": 0.15, "totalAssets": null, "totalEquity": 235324.0, "deposits": null, "loans": null, "ebitda": null, "mpesa": null}
    ],
  },

  DTK: {
    name: "Diamond Trust Bank Kenya",
    ticker: "DTK",
    exchange: "NSE",
    sector: "Banking",
    logo: "\ud83c\udfe6",
    currency: "KES",
    units: "thousands",
    latestPrice: 60.0,
    latestPeriod: {"year": 2022, "period": "H1 Jun2022", "periodType": "half_year", "revenue": 15045146.0, "pat": 12326771.0, "pbt": 5674647.0, "nii": 59487.0, "eps": null, "dps": null, "totalAssets": 485040585.0, "totalEquity": 76606716.0, "deposits": 32055184.0, "loans": 233621787.0, "ebitda": null, "mpesa": null},
    annuals: [
      {"year": 2021, "period": "Dec2021", "periodType": "annual", "revenue": 6835347.0, "pat": 3908411.0, "pbt": 6416672.0, "nii": 19992573.0, "eps": null, "dps": null, "totalAssets": 456842717.0, "totalEquity": 74552984.0, "deposits": 25266128.0, "loans": null, "ebitda": null, "mpesa": null},
      {"year": 2023, "period": "Dec2023", "periodType": "annual", "revenue": 5823533.0, "pat": 6879176.0, "pbt": 425708.0, "nii": 36138804.0, "eps": 24.6, "dps": null, "totalAssets": 635040842.0, "totalEquity": 86351524.0, "deposits": 22012540.0, "loans": 12248834.0, "ebitda": null, "mpesa": null},
      {"year": 2024, "period": "Dec2024", "periodType": "annual", "revenue": null, "pat": 7642442.0, "pbt": 11270093.0, "nii": null, "eps": null, "dps": null, "totalAssets": null, "totalEquity": null, "deposits": null, "loans": null, "ebitda": null, "mpesa": null}
    ],
  },

  EQTY: {
    name: "Equity Group Holdings PLC",
    ticker: "EQTY",
    exchange: "NSE",
    sector: "Banking",
    logo: "\ud83c\udfe6",
    currency: "KES",
    units: "thousands",
    latestPrice: 52.0,
    latestPeriod: {"year": 2025, "period": "Q Sep2025", "periodType": "quarter", "revenue": 65849444.0, "pat": null, "pbt": null, "nii": 42043892.0, "eps": 685.31, "dps": null, "totalAssets": 985388288.0, "totalEquity": 126070494.0, "deposits": 607951110.0, "loans": 423197110.0, "ebitda": null, "mpesa": null},
    annuals: [
      {"year": 2020, "period": "Dec2020", "periodType": "annual", "revenue": null, "pat": null, "pbt": null, "nii": 34415412.0, "eps": 624.79, "dps": null, "totalAssets": null, "totalEquity": 69914370.0, "deposits": 380603583.0, "loans": 276863043.0, "ebitda": null, "mpesa": null},
      {"year": 2021, "period": "Dec2021", "periodType": "annual", "revenue": null, "pat": 39175.0, "pbt": null, "nii": null, "eps": null, "dps": null, "totalAssets": null, "totalEquity": null, "deposits": null, "loans": null, "ebitda": null, "mpesa": null},
      {"year": 2023, "period": "Dec2023", "periodType": "annual", "revenue": 85951042.0, "pat": null, "pbt": null, "nii": 58411267.0, "eps": 1113.13, "dps": null, "totalAssets": 894011760.0, "totalEquity": 97527391.0, "deposits": 517217504.0, "loans": 429821383.0, "ebitda": null, "mpesa": null},
      {"year": 2024, "period": "Dec2024", "periodType": "annual", "revenue": 90267186.0, "pat": null, "pbt": null, "nii": 57214481.0, "eps": 888.89, "dps": null, "totalAssets": 1004243929.0, "totalEquity": 100766641.0, "deposits": 609677691.0, "loans": 448741110.0, "ebitda": null, "mpesa": null}
    ],
  },

  FANB: {
    name: "Family Bank Ltd",
    ticker: "FANB",
    exchange: "NSE",
    sector: "Banking",
    logo: "\ud83c\udfe6",
    currency: "KES",
    units: "thousands",
    latestPrice: 6.2,
    latestPeriod: {"year": 2020, "period": "Q Sep2020", "periodType": "quarter", "revenue": 5582717.0, "pat": 665915.0, "pbt": 951307.0, "nii": 3613637.0, "eps": 0.52, "dps": 0.24, "totalAssets": 78926424.0, "totalEquity": 12092368.0, "deposits": 60431181.0, "loans": 49336332.0, "ebitda": null, "mpesa": null},
    annuals: [
      {"year": 2021, "period": "Dec2021", "periodType": "annual", "revenue": 8927472.0, "pat": 1076047.0, "pbt": 1325613.0, "nii": 6406043.0, "eps": 0.84, "dps": null, "totalAssets": 90590626.0, "totalEquity": 13161565.0, "deposits": 70125378.0, "loans": 56579798.0, "ebitda": null, "mpesa": null}
    ],
  },

  JUB: {
    name: "Jubilee Holdings Limited",
    ticker: "JUB",
    exchange: "NSE",
    sector: "Insurance",
    logo: "\ud83c\udfe2",
    currency: "KES",
    units: "thousands",
    latestPrice: 230.0,
    latestPeriod: {"year": 2024, "period": "H1 Jun2024", "periodType": "half_year", "revenue": null, "pat": null, "pbt": null, "nii": null, "eps": 34.45, "dps": null, "totalAssets": null, "totalEquity": null, "deposits": null, "loans": null, "ebitda": null, "mpesa": null},
    annuals: [
      {"year": 2021, "period": "Dec2021", "periodType": "annual", "revenue": null, "pat": 6828655.0, "pbt": null, "nii": null, "eps": 89.88, "dps": null, "totalAssets": 155272618.0, "totalEquity": null, "deposits": null, "loans": null, "ebitda": null, "mpesa": null},
      {"year": 2024, "period": "Dec2024", "periodType": "annual", "revenue": 25676005.0, "pat": 4792620.0, "pbt": 6224690.0, "nii": null, "eps": null, "dps": null, "totalAssets": 213577754.0, "totalEquity": 51182318.0, "deposits": null, "loans": null, "ebitda": null, "mpesa": null}
    ],
  },

  KCB: {
    name: "KCB Group PLC",
    ticker: "KCB",
    exchange: "NSE",
    sector: "Banking",
    logo: "\ud83c\udfe6",
    currency: "KES",
    units: "thousands",
    latestPrice: 42.0,
    latestPeriod: {"year": 2025, "period": "Q Sep2025", "periodType": "quarter", "revenue": 98811027.0, "pat": null, "pbt": null, "nii": 72146888.0, "eps": 0.83, "dps": 0.12, "totalAssets": 1404190326.0, "totalEquity": 210325777.0, "deposits": 1062960998.0, "loans": 850344983.0, "ebitda": null, "mpesa": null},
    annuals: [
      {"year": 2020, "period": "Dec2020", "periodType": "annual", "revenue": 75842577.0, "pat": null, "pbt": 25589.0, "nii": 53470863.0, "eps": 0.34, "dps": 0.17, "totalAssets": 758345431.0, "totalEquity": 111270544.0, "deposits": 588627915.0, "loans": 492537561.0, "ebitda": null, "mpesa": null},
      {"year": 2023, "period": "Dec2023", "periodType": "annual", "revenue": 98100692.0, "pat": null, "pbt": null, "nii": 64774792.0, "eps": 0.47, "dps": 0.58, "totalAssets": 1425369827.0, "totalEquity": 138717804.0, "deposits": 1116875397.0, "loans": 740241723.0, "ebitda": null, "mpesa": null},
      {"year": 2024, "period": "Dec2024", "periodType": "annual", "revenue": 126653268.0, "pat": null, "pbt": null, "nii": 88856198.0, "eps": 0.83, "dps": 0.24, "totalAssets": 1277766539.0, "totalEquity": 183715437.0, "deposits": 971960594.0, "loans": 736614026.0, "ebitda": null, "mpesa": null}
    ],
  },

  NMG: {
    name: "Nation Media Group",
    ticker: "NMG",
    exchange: "NSE",
    sector: "Media",
    logo: "\ud83d\udcf0",
    currency: "KES",
    units: "thousands",
    latestPrice: 14.0,
    latestPeriod: {"year": 2024, "period": "H1 Jun2024", "periodType": "half_year", "revenue": null, "pat": null, "pbt": null, "nii": null, "eps": -1.5, "dps": null, "totalAssets": null, "totalEquity": 7195.07, "deposits": null, "loans": null, "ebitda": null, "mpesa": null},
    annuals: [
      {"year": 2020, "period": "Dec2020", "periodType": "annual", "revenue": 6812.89, "pat": 48.1, "pbt": null, "nii": null, "eps": 0.24, "dps": 1.5, "totalAssets": null, "totalEquity": 7933.07, "deposits": null, "loans": null, "ebitda": null, "mpesa": null},
      {"year": 2021, "period": "Dec2021", "periodType": "annual", "revenue": 7.6, "pat": 491.8, "pbt": null, "nii": null, "eps": 2.5, "dps": 1.5, "totalAssets": null, "totalEquity": 578.3, "deposits": null, "loans": null, "ebitda": null, "mpesa": null},
      {"year": 2023, "period": "Dec2023", "periodType": "annual", "revenue": 2.5, "pat": null, "pbt": null, "nii": null, "eps": -1.1, "dps": 1.5, "totalAssets": null, "totalEquity": null, "deposits": null, "loans": null, "ebitda": null, "mpesa": null}
    ],
  },

  NCBA: {
    name: "NCBA Group PLC",
    ticker: "NCBA",
    exchange: "NSE",
    sector: "Banking",
    logo: "\ud83c\udfe6",
    currency: "KES",
    units: "thousands",
    latestPrice: 45.0,
    latestPeriod: {"year": 2025, "period": "Q Sep2025", "periodType": "quarter", "revenue": 43379462.0, "pat": 13586632.0, "pbt": 16813968.0, "nii": 28641705.0, "eps": 25.02, "dps": 11.97, "totalAssets": 571339821.0, "totalEquity": 99792458.0, "deposits": 431595859.0, "loans": 257358575.0, "ebitda": null, "mpesa": null},
    annuals: [
      {"year": 2020, "period": "Dec2020", "periodType": "annual", "revenue": 41233774.0, "pat": 5161865.0, "pbt": 6954686.0, "nii": 22527748.0, "eps": 9.51, "dps": 4.88, "totalAssets": 491613725.0, "totalEquity": 72028375.0, "deposits": 389484170.0, "loans": 224420668.0, "ebitda": null, "mpesa": null},
      {"year": 2021, "period": "Dec2021", "periodType": "annual", "revenue": null, "pat": null, "pbt": null, "nii": null, "eps": 20.96, "dps": 6.08, "totalAssets": null, "totalEquity": null, "deposits": null, "loans": null, "ebitda": null, "mpesa": null}
    ],
  },

  SCOM: {
    name: "Safaricom PLC",
    ticker: "SCOM",
    exchange: "NSE",
    sector: "Telecoms",
    logo: "\ud83d\udce1",
    currency: "KES",
    units: "millions",
    latestPrice: 15.85,
    latestPeriod: {"year": 2024, "period": "Q Sep2024", "periodType": "quarter", "revenue": 179923.9, "pat": 10012.13, "pbt": 33859.25, "nii": null, "eps": 0.7, "dps": null, "totalAssets": 483124.4, "totalEquity": 189672.9, "deposits": null, "loans": null, "ebitda": null, "mpesa": 16.6},
    annuals: [
      {"year": 2020, "period": "Mar2020", "periodType": "annual", "revenue": 251220.0, "pat": 73660.0, "pbt": 105770.0, "nii": null, "eps": 1.84, "dps": 1.4, "totalAssets": null, "totalEquity": 143080.0, "deposits": null, "loans": null, "ebitda": 138040.0, "mpesa": null},
      {"year": 2023, "period": "Mar2023", "periodType": "annual", "revenue": 295692.3, "pat": 52482.87, "pbt": 88345.2, "nii": null, "eps": 1.55, "dps": 1.2, "totalAssets": 509207.0, "totalEquity": 263365.9, "deposits": null, "loans": null, "ebitda": 139862.4, "mpesa": 8.8},
      {"year": 2024, "period": "Mar2024", "periodType": "annual", "revenue": 335353.1, "pat": 42658.45, "pbt": 84687.49, "nii": null, "eps": 1.57, "dps": null, "totalAssets": 641164.3, "totalEquity": 335747.9, "deposits": null, "loans": null, "ebitda": -12776.5, "mpesa": 19.4}
    ],
  },

  CFC: {
    name: "I&M Group PLC",
    ticker: "CFC",
    exchange: "NSE",
    sector: "Banking",
    logo: "\ud83c\udfe6",
    currency: "KES",
    units: "thousands",
    latestPrice: 24.0,
    latestPeriod: {"year": 2025, "period": "H1 Jun2025", "periodType": "half_year", "revenue": 19448635.0, "pat": 108386582.0, "pbt": 8607882.0, "nii": 11827333.0, "eps": 16.56, "dps": 3.8, "totalAssets": 473718726.0, "totalEquity": 74265288.0, "deposits": null, "loans": null, "ebitda": null, "mpesa": null},
    annuals: [
      {"year": 2020, "period": "Dec2020", "periodType": "annual", "revenue": 23237370.0, "pat": 5192240.0, "pbt": 6227154.0, "nii": 12795161.0, "eps": 13.13, "dps": 3.8, "totalAssets": 328594515.0, "totalEquity": 51730956.0, "deposits": null, "loans": 196300029.0, "ebitda": null, "mpesa": null},
      {"year": 2021, "period": "Dec2021", "periodType": "annual", "revenue": 24990145.0, "pat": 7208090.0, "pbt": 9755739.0, "nii": 14373200.0, "eps": 18.23, "dps": null, "totalAssets": 328871809.0, "totalEquity": 56453027.0, "deposits": null, "loans": 229321277.0, "ebitda": null, "mpesa": null},
      {"year": 2023, "period": "Dec2023", "periodType": "annual", "revenue": 41316426.0, "pat": 12157619.0, "pbt": 17093925.0, "nii": 25647468.0, "eps": 30.75, "dps": 15.35, "totalAssets": 459283854.0, "totalEquity": 68554365.0, "deposits": null, "loans": 356214137.0, "ebitda": null, "mpesa": null}
    ],
  },

  SCBK: {
    name: "Standard Chartered Bank Kenya",
    ticker: "SCBK",
    exchange: "NSE",
    sector: "Banking",
    logo: "\ud83c\udfe6",
    currency: "KES",
    units: "thousands",
    latestPrice: 195.0,
    latestPeriod: {"year": 2022, "period": "H1 Jun2022", "periodType": "half_year", "revenue": 14112995.0, "pat": 9043839.0, "pbt": 7569331.0, "nii": 9115386.0, "eps": 12.69, "dps": 19.0, "totalAssets": 345646341.0, "totalEquity": 51706369.0, "deposits": 278186884.0, "loans": 130275654.0, "ebitda": null, "mpesa": null},
    annuals: [
      {"year": 2023, "period": "Dec2023", "periodType": "annual", "revenue": 33977048.0, "pat": 12057935.0, "pbt": 17103199.0, "nii": 22223065.0, "eps": 31.47, "dps": 22.0, "totalAssets": 381260015.0, "totalEquity": 56136730.0, "deposits": 278879309.0, "loans": 139412560.0, "ebitda": null, "mpesa": null},
      {"year": 2024, "period": "Dec2024", "periodType": "annual", "revenue": 41728586.0, "pat": 13835467.0, "pbt": 19668482.0, "nii": 29325087.0, "eps": 36.17, "dps": 29.0, "totalAssets": 428962175.0, "totalEquity": 61532267.0, "deposits": 342853241.0, "loans": 163161777.0, "ebitda": null, "mpesa": null}
    ],
  },

  UNGA: {
    name: "Unga Group Limited",
    ticker: "UNGA",
    exchange: "NSE",
    sector: "Agriculture",
    logo: "\ud83c\udf3e",
    currency: "KES",
    units: "thousands",
    latestPrice: 26.0,
    latestPeriod: {"year": 2021, "period": "H1 Jun2021", "periodType": "half_year", "revenue": 17812638.0, "pat": 293477.0, "pbt": 485232.0, "nii": null, "eps": 2.39, "dps": null, "totalAssets": 10048779.0, "totalEquity": 10048779.0, "deposits": null, "loans": null, "ebitda": null, "mpesa": null},
    annuals: [
      {"year": 2021, "period": "Dec2021", "periodType": "annual", "revenue": 8822553.0, "pat": null, "pbt": -16743.0, "nii": null, "eps": 0.003, "dps": null, "totalAssets": 9905921.0, "totalEquity": 9905921.0, "deposits": null, "loans": null, "ebitda": null, "mpesa": null},
      {"year": 2023, "period": "Dec2023", "periodType": "annual", "revenue": 12426424.0, "pat": null, "pbt": null, "nii": null, "eps": -2.49, "dps": null, "totalAssets": 10900009.0, "totalEquity": 10900009.0, "deposits": null, "loans": null, "ebitda": null, "mpesa": null}
    ],
  },

  EABL: {
    name: "East African Breweries Ltd",
    ticker: "EABL",
    exchange: "NSE",
    sector: "FMCG",
    logo: "\ud83c\udf7a",
    currency: "KES",
    units: "thousands",
    latestPrice: 155.0,
    latestPeriod: {"year": 2024, "period": "H1 Jun2024", "periodType": "half_year", "revenue": null, "pat": 10900000.0, "pbt": null, "nii": null, "eps": 10.3, "dps": null, "totalAssets": null, "totalEquity": null, "deposits": null, "loans": null, "ebitda": null, "mpesa": null},
    annuals: [
      {"year": 2021, "period": "Dec2021", "periodType": "annual", "revenue": null, "pat": null, "pbt": null, "nii": null, "eps": 8.45, "dps": null, "totalAssets": null, "totalEquity": null, "deposits": null, "loans": null, "ebitda": null, "mpesa": null},
      {"year": 2023, "period": "Dec2023", "periodType": "annual", "revenue": null, "pat": 6800000.0, "pbt": null, "nii": null, "eps": 13.8, "dps": null, "totalAssets": null, "totalEquity": null, "deposits": null, "loans": null, "ebitda": null, "mpesa": null}
    ],
  },

  NSE: {
    name: "Nairobi Securities Exchange",
    ticker: "NSE",
    exchange: "NSE",
    sector: "Other",
    logo: "\ud83d\udcc8",
    currency: "KES",
    units: "thousands",
    latestPrice: 7.0,
    latestPeriod: {"year": 2024, "period": "H1 Jun2024", "periodType": "half_year", "revenue": 429468.0, "pat": 54720.0, "pbt": 80007.0, "nii": null, "eps": 0.21, "dps": null, "totalAssets": 2116337.0, "totalEquity": null, "deposits": null, "loans": null, "ebitda": null, "mpesa": null},
    annuals: [
      {"year": 2021, "period": "Dec2021", "periodType": "annual", "revenue": 960969.0, "pat": null, "pbt": null, "nii": null, "eps": null, "dps": null, "totalAssets": 31953.0, "totalEquity": 15091.0, "deposits": null, "loans": null, "ebitda": null, "mpesa": null}
    ],
  }

};
